# _Data Analysis with Pandas - Solutions_
_Bu ödevde, pandas kütüphanesini kullanarak müşteri ve satış verilerini okuduk, işledik ve analiz ettik.  
Amaç, veri okuma, filtreleme, sütun ve satır seçimleri, merge, groupby, ve en çok harcayan müşteriyi bulma gibi temel veri analizi tekniklerini uygulamaktır._

## _Import_

In [1]:
import pandas as pd

## _Veri Okuma_

### _Virgülle ayrılmış "client_list.csv" dosyasını okuyun. Dosyayı bir değişkene atayın df1._

In [2]:
df1 = pd.read_csv("client_list.csv")  # CSV dosyasını okuyup df1'e atar

### _Sınırlandırılmış "client_list.table" dosyasını okuyun. Dosyayı bir değişken olarak atayın df2._

In [3]:
df2 = pd.read_csv("client_list.table", sep=';')

### _Sabit genişlikli "client_list.txt" dosyasını okuyun. Değişken olarak atayın.df3_

In [4]:
df3 = pd.read_fwf("client_list.txt")

### _Virgülle ayrılmış "client_list.csv" dosyasını okuyun, ilk 3 satırı atlayın ve başlığı yok sayın. Değişkene değer atamayın (sadece bir görünüm döndürün)._

In [5]:
pd.read_csv("client_list.csv", skiprows=3, header=None)

           0         1  2   3       4      5
0    Michael   Johnson  M  55     red  green
1       Mary     Adams  F  42  blonde   blue
2     Robert  Phillips  M  37  blonde  brown
3     Thomas     Moore  M  60   brown   blue
4    Natalie    Potter  F  21   brown  green
5     Brenda     Jones  F  18  blonde  brown
6    Michael     Smith  M  58   brown  brown
7   Jennifer     Smith  F  36   black  brown
8    Michael     Smith  M  37   black  hazel
9    Jessica    Rabbit  F  19   black   blue
10     Molly    Bryant  F  21   brown   blue
11     Jaime  Anderson  F  46   brown  green

### _Virgülle ayrılmış "client_list.csv" dosyasını okuyun. Sütun başlıklarını büyük harflerle yazın. Değişken olarak atayın df_

In [6]:
df = pd.read_csv("client_list.csv").rename(columns=str.upper)  # CSV'yi okuyup sütun isimlerini tek adımda büyük harfe çevirir

In [7]:
df.head(1)

  FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
0   Jennifer     Jones      F   27      black     brown

### _Virgülle ayrılmış "client_list_practice.csv" dosyasını okuyun ve yalnızca sütunları çıkarın ["FIRST_NAME","AGE","EYE_COLOR"]. Bir değişkene atamayın._

In [8]:
pd.read_csv("client_list_practice.csv", usecols=["FIRST_NAME", "AGE", "EYE_COLOR"])  # CSV'den sadece belirtilen sütunları okur

   FIRST_NAME   AGE EYE_COLOR
0    Jennifer  27.0     brown
1       Jaime  32.0     hazel
2     Michael  55.0     green
3        Mary  42.0       NaN
4         NaN  37.0     brown
5      Thomas  60.0      blue
6     Natalie   NaN     green
7      Brenda   NaN     brown
8     Michael  58.0     brown
9    Jennifer  36.0     brown
10    Michael  37.0     hazel
11    Jessica  19.0      blue
12      Molly  21.0      blue
13      Jaime  46.0     green

## _Bir Veri Kümesini Dilimleme_

### _df dosyasının 5. ila 11. satırlarını dilimleyin. Bunu yapmanın iki yolunu gösterebilir misiniz?_

In [9]:
df[4:11]

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
4      Robert  Phillips      M   37     blonde     brown
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel

In [10]:
df.iloc[4:11]  # 5-11. satırları index bazlı (0'dan başladığı için 4:11) dilimler

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
4      Robert  Phillips      M   37     blonde     brown
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel

In [11]:
df.loc[4:10]  # 5-11. satırları etiket bazlı (bitiş dahil) seçer

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
4      Robert  Phillips      M   37     blonde     brown
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel

### _Yalnızca ['SOYADI','YAŞ','SAÇ RENGİ'] sütunlarını döndürün df. Bunu yapmanın iki yolunu gösterebilir misiniz?_

In [12]:
df[["LAST_NAME", "AGE", "HAIR_COLOR"]]  # Belirtilen sütunları doğrudan seçer

   LAST_NAME  AGE HAIR_COLOR
0      Jones   27      black
1    Roberts   32      brown
2    Johnson   55        red
3      Adams   42     blonde
4   Phillips   37     blonde
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black
11    Rabbit   19      black
12    Bryant   21      brown
13  Anderson   46      brown

In [13]:
df.loc[:, ["LAST_NAME", "AGE", "HAIR_COLOR"]]  # Tüm satırlar için seçili sütunları etiket bazlı getirir

   LAST_NAME  AGE HAIR_COLOR
0      Jones   27      black
1    Roberts   32      brown
2    Johnson   55        red
3      Adams   42     blonde
4   Phillips   37     blonde
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black
11    Rabbit   19      black
12    Bryant   21      brown
13  Anderson   46      brown

### _7 ve 8 numaralı problemleri birleştirin: . için 5'ten 11'e kadar olan satırları ve ['SOYADI','YAŞ','SAÇ RENGİ'] sütunlarını döndürün df. Bunu yapmanın iki yolunu gösterebilir misiniz?_

In [14]:
df.loc[4:10, ["LAST_NAME", "AGE", "HAIR_COLOR"]]  # Satır ve sütunları tek adımda etiket bazlı seçer

   LAST_NAME  AGE HAIR_COLOR
4   Phillips   37     blonde
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black

In [15]:
df[4:11][['LAST_NAME','AGE','HAIR_COLOR']]

   LAST_NAME  AGE HAIR_COLOR
4   Phillips   37     blonde
5      Moore   60      brown
6     Potter   21      brown
7      Jones   18     blonde
8      Smith   58      brown
9      Smith   36      black
10     Smith   37      black

## _Basit Sorgular_

### _dfSoyadı "Smith" olan müşterilerin alt kümesini bulun ._

In [16]:
df.query("LAST_NAME == 'Smith'")  # Soyadı Smith olan satırları daha okunabilir şekilde filtreler

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
8     Michael     Smith      M   58      brown     brown
9    Jennifer     Smith      F   36      black     brown
10    Michael     Smith      M   37      black     hazel

### _dfMüşterinin saç renginin siyah olmadığı alt kümeyi bulun ._

In [17]:
df[df.HAIR_COLOR.ne("black")]  # Saç rengi siyah olmayanları kısa ve temiz şekilde seçer

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
1       Jaime   Roberts      M   32      brown     hazel
2     Michael   Johnson      M   55        red     green
3        Mary     Adams      F   42     blonde      blue
4      Robert  Phillips      M   37     blonde     brown
5      Thomas     Moore      M   60      brown      blue
6     Natalie    Potter      F   21      brown     green
7      Brenda     Jones      F   18     blonde     brown
8     Michael     Smith      M   58      brown     brown
12      Molly    Bryant      F   21      brown      blue
13      Jaime  Anderson      F   46      brown     green

### _dfMüşterinin saç renginin kırmızı olduğu alt kümeyi bulun ve değerleri "kızıl" olarak sıfırlayın._

In [18]:
df.loc[df.HAIR_COLOR=='red', 'HAIR_COLOR'] = "ginger"  # Saç rengi red olanları ginger olarak günceller

## _Karmaşık Sorgular_

### _dfMüşterilerin 30 yaşından büyük kadınlardan oluştuğu alt kümeyi bulun ._

In [19]:
df.query("AGE > 30 and GENDER == 'F'")  # 30 yaş üstü kadın müşterileri okunabilir şekilde filtreler

   FIRST_NAME LAST_NAME GENDER  AGE HAIR_COLOR EYE_COLOR
3        Mary     Adams      F   42     blonde      blue
9    Jennifer     Smith      F   36      black     brown
13      Jaime  Anderson      F   46      brown     green

### _13. problemi tekrarlayın, ancak yalnızca saç rengini ve göz rengini döndürün._

In [20]:
df.query("AGE > 30 and GENDER == 'F'")[["HAIR_COLOR", "EYE_COLOR"]]  # Filtre sonrası sadece istenen sütunları döndürür

   HAIR_COLOR EYE_COLOR
3      blonde      blue
9       black     brown
13      brown     green

### _25 yaş üstü kadınlar için eşsiz saç ve göz rengi kombinasyonunu bulun._

In [21]:
df.query("GENDER == 'F' and AGE > 25")[["HAIR_COLOR", "EYE_COLOR"]].drop_duplicates()  # 25 yaş üstü kadınlar için benzersiz saç-göz rengi kombinasyonlarını verir

   HAIR_COLOR EYE_COLOR
0       black     brown
3      blonde      blue
13      brown     green

## _Ek Veri Çerçevesi İşlemleri_

In [22]:
# CSV'leri oku ve sütun isimlerini büyük harfe çevir
df = pd.read_csv("client_list.csv").rename(columns=str.upper)
ids = pd.read_csv("customer_id_list.csv")

In [23]:
# Müşteri listelerini birleştir (merge)
clients = df.merge(ids, how="left", on=["LAST_NAME","FIRST_NAME","GENDER","AGE"])  # LEFT JOIN ile ID bilgilerini ekler

In [24]:
# Satış verilerini oku ve müşterilerle birleştir
sales = pd.read_csv("purchase_log.csv")
detailed_sales = clients.merge(sales, how="inner", on="CUSTOMER_ID")  # INNER JOIN ile sadece satın alma yapanları alır

In [25]:
# Müşterilerin toplam harcamasını hesapla
spenders = detailed_sales.groupby(
    ["CUSTOMER_ID","FIRST_NAME","LAST_NAME","GENDER","AGE"], as_index=False
)["PRICE"].sum()  # Her müşteri için toplam harcama

In [26]:
# En çok harcama yapan müşteriyi bul
top_spender = spenders.loc[spenders.PRICE.idxmax()]  # Maksimum PRICE değerine sahip satırı seçer

In [27]:
# BONUS: En çok harcayan müşterinin satın aldığı ürünleri listele
top_spender_items = sales.loc[sales.CUSTOMER_ID==top_spender.CUSTOMER_ID, "ITEM_DESCRIPTION"]  # Toplam harcayanın ürünleri

## _Dosya Yazma_

In [28]:
# detailed_sales veri çerçevesini CSV olarak kaydet (index olmadan)
detailed_sales.to_csv("df_out.csv", index=False)  # CSV dosyası oluşturur

In [29]:
# detailed_sales veri çerçevesini pickle formatında kaydet
detailed_sales.to_pickle("df_out.p")  # Pickle ile hızlı yüklenebilir veri dosyası oluşturur

---

## _Özet ve Sonuç_
- _CSV ve pickle dosyaları ile veri okuma ve kaydetme işlemleri gerçekleştirildi._  
- _Filtreleme, dilimleme ve sütun seçimleri ile alt kümeler oluşturuldu._  
- _Müşteri verileri ile satış verileri birleştirildi (merge)._  
- _Groupby ve sum ile toplam harcama hesaplandı, en çok harcayan müşteri belirlendi._  
- En çok harcayan müşterinin hangi ürünleri satın aldığı tespit edildi._